#!/bin/bash

IFACE="$1"
STATUS="$2"
TARGET_SSID="AMKBr"

if [ "$STATUS" = "up" ]; then
    CURRENT_SSID=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2)
    if [ "$CURRENT_SSID" = "$TARGET_SSID" ]; then
        /bin/amk/smbcred.sh >> /tmp/smbcred.log 2>&1
    fi
fi
